src/firewall/core/fw_direct.py
This fixes #12.
Signed-off-by: Mathieu Le Marec - Pasquet <kiorky@cryptelium.net>
=> Fix rule id

src/firewall/core/ebtables.py, src/firewall/core/fw.py, src/firewall/core/fw_config.py, src/firewall/core/fw_direct.py, src/firewall/core/fw_icmptype.py, src/firewall/core/fw_policies.py, src/firewall/core/fw_service.py, src/firewall/core/fw_test.py, src/firewall/core/fw_zone.py, src/firewall/core/io/direct.py, src/firewall/core/io/firewalld_conf.py, src/firewall/core/io/io_object.py, src/firewall/core/io/lockdown_whitelist.py, src/firewall/core/io/zone.py, src/firewall/core/ipXtables.py, src/firewall/core/logger.py, src/firewall/core/modules.py, src/firewall/core/rich.py, src/firewall/dbus_utils.py, src/firewall/functions.py, src/firewall/fw_types.py, src/firewall/server/config.py, src/firewall/server/decorators.py, src/firewall/server/firewalld.py, src/gtk3_chooserbutton.py
minor issues, nothing important
=> Fix flaws found by landscape.io

src/firewall/core/fw_direct.py
This refs #12 #13
This fixes #14
Signed-off-by: Mathieu Le Marec - Pasquet <kiorky@cryptelium.net>
=> Another attempt to fix reload with direct rules.

src/firewalld
This fixes #19
Signed-off-by: Mathieu Le Marec - Pasquet <kiorky@cryptelium.net>
=> Be sure that the pid file exists

config/services/pulseaudio.xml
Signed-off-by: Igor Gnatenko <ignatenko@src.gnome.org>
=> services: add pulseaudio

config/services/imap.xml, config/services/pop3.xml
Could you merge my patch?
This request related by Bugzilla Bz#1062993
https://bugzilla.redhat.com/show_bug.cgi?id=1062993
=> pop3.xml: Added POP-3 service(Non SSL)

.travis.yml
=> Adding Travis-CI configuration file

doc/xml/firewalld.service.xml
=> Trivial typo.

config/services/klogin.xml, config/services/kshell.xml
This PR adds some of the kerberos remote shell programs that hang around in (at least my) legacy environments.
=> Added kerberos remote shells

config/services/ganglia-client.xml, config/services/ganglia-master.xml
This PR adds most of the ganglia services.
=> Added ganglia ports

config/services/sip.xml, config/services/sips.xml
Similar to what is found in the FTP services.
But I welcome comments on whether or not this is a good idea.
=> Adding nf_conntrack_sip module

config/firewall-config.appdata.xml.in
I've been asked by Richard Hughes to update the AppData config file so I ran
`appstream-util upgrade firewall-config.appdata.xml.in`
filled the new metadata fields and here's the result.
=> Update AppData configuration file.

config/services/condor-collector.xml
Added service for the central condor master.
=> Add condor collector service

config/services/cfengine.xml, config/services/smtp-submission.xml
used for the CFEngine...
add 5308/tcp for cfengine service
=> Add CFEngine service.

config/services/kibana.xml
used for the ELK stack...
add 5601/tcp for kibana service
=> add kibana service

config/services/elasticsearch.xml
Part of the ELK stack...
adding 9200/tcp for elasticsearch restful api
adding 9300/tcp for elasticsearch transport
=> add elasticsearch service

config/services/spideroak-lansync.xml
I wrote service XML file for SpiderOak LAN-Sync.
Could you merge my patch?
=> spideroak-lansync.xml: Added SpiderOak LAN-Sync service

config/Makefile.am, config/services/minidlna.xml
Added Service definition for MiniDLNA
=> minidlna definitions

.travis.yml, config/xmlschema/check.sh
Check xml definition of zones, services, icmptypes and ipsets with config/xmlschema/check.sh for correctness with Travis Ci
=> Add checks of xml configs with Travis Ci

config/Makefile.am, config/services/bgp.xml
using name simplified automation and integration with puppet modules.
=> add bgp service to predefined services

doc/xml/firewall-cmd.xml, src/firewall-offline-cmd, src/firewall/command.py, src/firewall/core/fw.py, src/firewall/core/fw_icmptype.py
Hi Eric,
This branch contains fixes for the following BZs:
- RHBZ#1452137
- RHBZ#1479951
- RHBZ#1368544
- RHBZ#1372716
- RHBZ#1445214
Cheers, Phil
=> Upstream queue

config/Makefile.am, config/services/zabbix-agent.xml, config/services/zabbix-server.xml
opening tcp port 10050 for zabbix agent and 10051 for zabbix server in two separate files.
=> Adding firewalld zabbix server and agent services

config/Makefile.am, config/services/redis.xml
opening tcp port 6379 for redis
=> Adding FirewallD redis service

src/firewall/core/fw.py, src/firewall/core/fw_direct.py, src/firewall/core/fw_test.py, src/firewall/core/fw_transaction.py, src/firewall/core/ipXtables.py
Hi @n0-1,
This is some more refactoring to help with iptables abstraction. Please review. :)
- fw_direct
- fw_transaction
=> More iptables abstractions

config/Makefile.am, config/services/amqp.xml, config/services/amqps.xml
This commit adds service definitions for AMQP and AMQPS.
=> services/amqp: Add AMQP and AMQPS services

config/Makefile.am, config/services/plex.xml
https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?search=32400
=> Add Plex service

config/Makefile.am, config/services/matrix-synapse.xml, config/services/matrix.xml
See https://github.com/matrix-org/synapse#using-a-reverse-proxy-with-synapse
=> Add matrix service

config/Makefile.am, config/services/samba-dc.xml, po/POTFILES.in
IP port reference: https://wiki.samba.org/index.php/Samba_AD_DC_Port_Usage
=> New samba-dc service

src/firewall-applet.in, src/firewall-config.in, src/firewall/core/fw_nm.py
Preceded by some NetworkManager API improvements.
=> Avoid telling NetworkManager to modify generated connections

src/firewall/core/ipXtables.py
=> Rich Rule Masquerade inverted source-destination in Forward Chain #278

src/firewall-cmd, src/firewall/command.py, src/firewall/core/fw_nm.py, src/firewall/core/fw_zone.py, src/firewall/server/config_zone.py, src/firewall/server/firewalld.py
Hello,
These backported patches are needed in order for firewalld-0.5.X to work better with NetworkManager
=> NM backported fixes

config/services/steam-streaming.xml
See the changelog for 2018-10-11 at https://store.steampowered.com/news/?feed=steam_client
=> services/steam-streaming: update udp ports

config/services/plex.xml
As specified here: https://support.plex.tv/articles/201543147-what-network-ports-do-i-need-to-allow-through-my-firewall/
=> Added additional network ports to plex

config/Makefile.am, config/services/kube-apiserver.xml, po/POTFILES.in
opening tcp port 6443 for K8s api server.
=> add kube-apiserver service

doc/xml/firewalld.dbus.xml, shell-completion/bash/firewall-cmd, shell-completion/zsh/_firewalld, src/firewall-cmd.in, src/firewall-offline-cmd.in, src/firewall/client.py, src/firewall/command.py, src/firewall/core/fw_config.py, src/firewall/core/fw_zone.py, src/firewall/core/io/io_object.py, src/firewall/core/io/service.py, src/firewall/core/io/zone.py, src/firewall/core/ipXtables.py, src/firewall/core/nftables.py, src/firewall/server/config.py, src/firewall/server/config_zone.py, src/firewall/server/firewalld.py, src/tests/cli/firewall-cmd.at, src/tests/dbus/service.at, src/tests/dbus/zone_permanent_functional.at, src/tests/dbus/zone_permanent_signatures.at, src/tests/dbus/zone_runtime_functional.at, src/tests/dbus/zone_runtime_signatures.at
This supersedes #586. It includes all the necessary API changes and extra tests. Only one of the commits is actually from #586.
@danc86, if you get a chance can you test this out and/or review your commit from pr #586. I made changes to use the new API.
=> feature: forwarding between interfaces in a zone

config/Makefile.am, config/services/collectd.xml, po/POTFILES.in
I added the missing service collectd.
=> Add collectd service

config/Makefile.am, config/services/rquotad.xml, po/POTFILES.in
Signed-off-by: Kenneth D'souza <kdsouza@redhat.com>
=> feat(service): Add rpc-rquotad.service

README
Updated the commit message and should be good to go
=> doc(README): add libxslt for doc generation

.travis.yml, src/tests/regression/rhbz1541077.at, src/tests/regression/rhbz1855140.at
Also fixes a couple test failures.
=> Travis fix python slip

src/tests/features/rich_tcp_mss_clamp.at
=> test(features/rich_tcp_mss_clamp): fix test to pass without debug flag

config/Makefile.am, config/services/galera.xml, po/POTFILES.in
=> feat(service): add galera service

src/firewall/core/fw_zone.py
Add zone name to the ZONE_CONLICT error message
Signed-off-by: Arko Dasgupta <arko.dasgupta@docker.com>
=> improvement(zone): Update error message

doc/xml/firewalld.conf.xml
=> docs(conf): note that IPv6_rpfilter has a performance penalty

doc/xml/firewalld.zone.xml, doc/xml/firewalld.zones.xml
Describe the Intra Zone Forwarding setting and its effect.
=> [WIP] docs(zones,zone): describe intra zone forwarding

doc/xml/firewalld.zones.xml
Add a description of ICMP block inversion to firewalld.zones(5)
=> docs(zones): describe ICMP block inversion

config/services/llmnr.xml
=> improvement(service): LLMNR: add destination addresses

config/services/minidlna.xml, config/services/plex.xml, config/services/ssdp.xml, config/services/upnp-client.xml
About...
https://github.com/firewalld/firewalld/blob/c11510e065fdbaeb8ff20f32e2628bdd70d30dd7/config/services/upnp-client.xml
can a service only include other?
=> services: ssdp includes

config/services/ms-wbt.xml
=> improvement(service): ms-wbt: use service include

config/Makefile.am, config/services/afp.xml, config/services/ws-discovery-tcp.xml, config/services/ws-discovery-udp.xml, config/services/ws-discovery.xml, po/POTFILES.in
@mymatenige if you do not mind this PR implements the requested changes from firewalld/firewalld#616 (with slight modification in the short description of each service). Kept your authorship in place.
=> Add AFP and WS-Discovery

config/Makefile.am, config/services/ws-discovery-client.xml, po/POTFILES.in
Analogous to 04d3aad12300b2c6148150992b14009fa6524d4d.
Fixes firewalld/firewalld#848
=> feat(service): add service definition for WS-Discovery Client

Dockerfile, Makefile.am, README
See commit message and README.
=> feat(build): distribute an OCI container image

config/Makefile.am, config/services/http3.xml, po/POTFILES.in
Expand the https service definition to include HTTP/3 (443/udp)
=> Add HTTP/3 service

Makefile.am, src/firewall/core/fw_policy.py, src/firewall/core/io/policy.py, src/firewall/core/ipXtables.py, src/firewall/core/nftables.py, src/tests/features/forward_ports.at, src/tests/features/policy.at
```
[root@vm-bos-rhel8-1 02]# sysctl net.ipv4.conf.all.route_localnet                                                                       
net.ipv4.conf.all.route_localnet = 1                                                                                                    
[root@vm-bos-rhel8-1 02]# firewall-cmd --info-policy fwdPortsFromHost                                                                   
fwdPortsFromHost (active)                                                                                                               
priority: -1                                                                                                                          
target: CONTINUE …
```
=> feat(policy): support OUTPUT forward ports

config/Makefile.am, config/services/zerotier.xml, po/POTFILES.in
ZeroTier creates secure networks between on-premise, cloud, desktop, and mobile devices.
=> Add ZeroTier service

.github/workflows/integration-testsuite.yml, src/tests/functions.at, src/tests/integration/rhbz1773809.at, src/tests/integration/rhbz1928860.at
Also cherry-picked a change I had laying around to enable integration tests in github CI.
=> test(nm): rhbz1928860: check for OVS support

config/Makefile.am, config/services/checkmk-agent.xml, po/POTFILES.in
This is a service definition for the check_mk-agent.
=> feat(service): add check_mk-agent service

config/Makefile.am, config/services/netdata-dashboard.xml, po/POTFILES.in
Add a service definition for netdata.
=> feat(service): add netdata service

config/Makefile.am, config/services/kodi-eventserver.xml, config/services/kodi-rpc.xml, po/POTFILES.in
https://kodi.wiki/view/JSON-RPC_API#TCP
https://kodi.wiki/view/EventServer#Event_Clients_and_the_EventServer
=> add Kodi JSON-RPC and EventServer services

README.md
Formatting quotation missing in 'README.md' and removed quotation from workflow url's
=> fix: missing format in 'README.md'

README.md
[35762fd](https://github.com/firewalld/firewalld/pull/983/commits/35762fd76fa1fed6795415e7d054cc33cc3ba023): Add newlines before/after headings and formatted text to improve readability. Also use markdown reference-style links.
[8235b89](https://github.com/firewalld/firewalld/commit/8235b89f5ca3c15dfd2091e1dd5f4159d3cfe26e): Render optional parameter `<ver>` properly
Closes: #981
=> improvement(readme): improve readability and add formatting

doc/xml/firewalld.richlanguage.xml, doc/xml/firewalld.zones.xml
=> docs: add protocols to rich and zones

doc/xml/policy_zone_descriptions.xml, doc/xml/policy_zone_syntax.xml
=> docs(policy): add priority attribute to rule

.github/ISSUE_TEMPLATE/config.yml
Improve the appearance of issue templates by using
capitalized names for the mailing lists.
=> improvement(github): improve appearance of list

src/firewall/core/io/functions.py
Instead of the runtime instance.
Fixes: d8ebe1da94d9 ("feat(policy): masquerade: allow ingress zone to have interface")
=> fix(check_config): use on disk firewalld_conf

src/firewall/client.py, src/firewall/core/nftables.py
Rather than just initiating exceptions, raise them instead, and fix the conditional statement issue that was discovered after raising an exception.
=> fix:  correct conditional statement and raise exceptions

src/firewall/core/fw.py, src/firewall/core/rich.py, src/firewall/errors.py, src/firewall/functions.py, src/firewall/server/decorators.py
Fix nested loop with duplicate variable name, remove unreachable code, and remove unnecessary passes and conditions.
=> improvement(code): improve code quality

src/firewall/core/ebtables.py, src/firewall/core/io/ipset.py, src/firewall/core/ipXtables.py, src/firewall/core/nftables.py, src/firewall/functions.py
Improve logic inside functions.
- 00f6e16: initialize rule fragment with tcp flags.
- 3b0fd03: prefer the usage of enumerate over range(len(x)).
- 26edb73: index delimiter position only once and call string boolean operator.
=> improvement: code quality

src/firewall/core/fw_policy.py
Raise exceptions rather than returning them.
=> fix(fw_policy): raise exceptions

config/Makefile.am, config/services/0-AD.xml, config/services/anno-1602.xml, config/services/anno-1800.xml, config/services/civilization-iv.xml, config/services/civilization-v.xml, config/services/factorio.xml, config/services/minecraft.xml, config/services/need-for-speed-most-wanted.xml, config/services/settlers-history-collection.xml, config/services/stellaris.xml, config/services/stronghold-crusader.xml, config/services/supertuxkart.xml, config/services/terraria.xml, config/services/zero-k.xml, po/POTFILES.in
- 0 A.D.
- Anno 1602
- Anno 1800
- Sid Meier's Civilization IV
- Sid Meier's Civilization V
- Factorio
- Minecraft
- Need for Speed: Most Wanted (2005)
- The Settlers History Collection
- Stellaris
- Stronghold Crusader
- SuperTuxKart
- Terraria
- Zero-K
=> feat(service): Add services for some games

config/Makefile.am, config/services/statsrv.xml, po/POTFILES.in
This service comes in handy at odd times...
=> feat(service): define statsrv from RFC 996

src/firewall-config.in
Second argument is ipset, third is invert flag.
Fixes: #1120
Fixes: 286d00031f43 ("feat(rich): support using ipset in destination")
=> fix(firewall-config): rich: set destination address

config/Makefile.am, config/services/dns-over-quic.xml, po/POTFILES.in
https://github.com/firewalld/firewalld/issues/1071
=> feat(service): add DNS over QUIC (DoQ) Service

src/firewall-config.in
=> fix(firewall-config): escape markup stored in bindings store

doc/xml/policy_zone_descriptions.xml, src/firewall/core/io/policy.py
See https://lists.fedorahosted.org/archives/list/firewalld-users@lists.fedorahosted.org/thread/7J423T2P5R3Y6ASNCN4HDPVHZUVHSYGD/
=> [th/fix-policy-tcp-mss-clamp] fix docs and validation error with <tcp-mss-clamp/> in policy

src/firewall-applet.in, src/firewall/client.py, src/firewall/dbus_utils.py, src/firewall/functions.py, src/tests/unit/test_dbus_utils.py
Currently looking how D-Bus is handled in client.py.
Trying to improve it somewhat.
=> [th/dbus-signals] cleanup handling of D-Bus signals in client.py

config/Makefile.am, config/services/vrrp.xml, po/POTFILES.in
Hi everybody, a better version of: https://github.com/firewalld/firewalld/pull/1254.
Regards,
=> feat(service): add vrrp

src/firewall/core/rich.py, src/tests/unit/test_rich_rule.py
=> [th/unittest-richrule] add unit tests for parsing rich rules

src/firewall/core/io/ipset.py, src/tests/cli/firewall-cmd.at, src/tests/regression/gh881.at
=> fix(io.ipset): raise exception if entries exceed limit

src/firewall/command.py, src/firewall/server/config.py
These patches are a dependency for an upcoming branch to drop the Lockdown feature.
As that branch may take a while to be merged (e.g. on when we deem it right to break the feature), these patches can go in earlier.
=> [th/various-for-deprecated-lockdown] various cleanup in preparation for dropping Lockdown feature

.github/workflows/source-checks.yml, README.md
- a3e10a0: show test results of all branches and releases.
- ad1d676: update workflow action versions for both action/checkout and action/setup-python.
=> ci(github): update badges and workflows

po/sl.po, src/firewall/functions.py, src/tests/unit/test_functions.py
Fixes https://github.com/firewalld/firewalld/issues/1310
=> [th/applet-translation-fix] fix sl.po translation and `firewall.functions.wrong_args_for_callable()`

po/as.po, po/bg.po, po/en_GB.po, po/gu.po, po/kn.po, po/ml.po, po/mr.po, po/ta.po, po/te.po, po/tr.po
=> Fix bad translation for "Interfaces" in several translations

config/Makefile.am, config/services/steam-lan-transfer.xml, po/POTFILES.in
Implements #1163 
https://help.steampowered.com/en/faqs/view/46BD-6BA8-B012-CE43
https://github.com/ValveSoftware/steam-for-linux/issues/9938
=> Added Steam LAN transfer service

config/firewall-config.appdata.xml.in
Update URL for translate , add URL for vcs-browser.
=> fix(appdata): Update URLs

config/Makefile.am, config/services/rootd.xml, po/POTFILES.in
This adds a service definition for the `xrootd` file service.
=> feat(service): xrootd file server

config/firewall-config.appdata.xml.in
See: https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-translation
=> fix(appdata): Add translation tag

config/Makefile.am, config/services/mpd.xml, po/POTFILES.in
Service description taken from its website <https://www.musicpd.org/>.
=> feat(service): add MPD (Music Player Daemon)

config/Makefile.am, config/services/aseqnet.xml, po/POTFILES.in
see http://www.alsa-project.org/files/pub/utils/alsa-utils-1.2.12.tar.bz2 alsa-utils-1.2.12/seq/aseqnet/aseqnet.c:49
```C
/*
* default TCP port number
*/
#define DEFAULT_PORT	"40002"
```
=> feat(service): add aseqnet

config/Makefile.am, config/services/gitea.xml, config/services/syslog-ng.xml, po/POTFILES.in
Gitea: Git with a cup of tea
A painless, self-hosted Git service
https://github.com/go-gitea/gitea
+ syslog-ng
https://wiki.archlinux.org/title/Syslog-ng
=> Create gitea.xmlservice file

config/Makefile.am, config/services/proxy-http.xml, config/services/socks.xml, po/POTFILES.in
https://github.com/firewalld/firewalld/issues/1389
=> feat(service): add proxy-http socks

config/Makefile.am
=> fix: include missing helper.xsd file to release tarball
