firewalld/firewalld

- config/icmptypes/timestamp-reply.xml
- config/icmptypes/timestamp-request.xml
The following ICMP types are not included by default in the available
configuration:
Type 13 - Timestamp Request [1]
Type 14 - Timestamp Request [1]
This is useful to address [2].
[1] http://tools.ietf.org/html/rfc792
[2] https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-1999-0524
> Add two missing ICMP types

- src/firewall/core/ebtables.py
- src/firewall/core/fw.py
- src/firewall/core/fw_direct.py
In firewalld, ebtables support was insufficient. These commits will add full ebtables support (we can now add direct rules as well as iptables and will not cause specific issues).
I personally use firewalld+ebtables in the gateway to filter some L2 traffic (e.g. ARP) and I hope minimum support of ebtables is added to firewalld (e.g. use direct rules **just like** ipXtables).
Tables in ebtables are not flushed and their policies are not changed on following events:
*  When firewalld is started/stopped
*  When firewalld is reloaded
*  When panic mode is enabled/disabled
I noticed this issue when I'm using `eb` passthroughs (I couldn't use direct rules because it lacks support of ebtables; I'm describing this issue in "Issue 2" section). Because `firewall-cmd --reload` doesn't flush tables …
> ebtables support

- src/firewall-cmd
- src/firewall-offline-cmd
Fixes two small typos in the firewall-cmd and firewall-offline-cmd help
text.
> Fix typos in firewall-cmd helptext

- config/Makefile.am
- config/services/ceph-mon.xml
- config/services/ceph.xml
Ceph's OSD and MDS daemons listen on TCP ports 6800 through 7300 by default.
Ceph's MON daemon listens on port 6789 by default.
This PR adds the "ceph" and "ceph-mon" service definitions for Ceph.
> add ceph services

- config/services/ipsec.xml
When a gateway is behind a NAT, ipsec uses port 4500/udp instead of 500/udp. Tested with StrongSwan.
> ipsec.service: add NAT-Traversal port

- config/services/docker-registry.xml
- config/services/docker.xml
I got tired of manually creating the services for docker and docker registry.
docker 2375/tcp used to remotely control docker servers
docker-registry 5000/tcp used to access docker registry servers
> add docker registry services

- config/services/smtps.xml
I wrote service XML file for SMTPs(SMTP over SSL), TCP port is 465
Currently, firewalld has service XML file for POP3s, IMAPs. But SMTPs is none.
Could you merge my patch?
> smtps.xml: Added SMTPs service

- src/firewall/core/io/firewalld_conf.py
Checking if the value for the IndividualCalls option is not empty is not
enough. We also need to check if the supplied value is a supported one
otherwise the value will silently be ignored if it is not 'true' or 'yes'
without feedback to the user.
Finally, refactor IndividualCalls code for consistency with the rest of
the options.
> src: core: firewalld_conf: Check if IndividualCalls value is supported

- .gitignore
- install-sh
- missing
'install-sh' and 'missing' files depend on the build host so they
shouldn't be part of the git sources. autogen.sh will normally regenerate
these by symlinking them from the system files so they may always appear
as modified when building firewalld from the checked out sources.
> Remove automake generated files

- src/Makefile.am
When performing a parallel installation on big systems, there is a race
condition when fix_python_shebang.sh is executed before the binaries are
installed leading to installation failures. Add missing dependencies to
fix this problem.
> src: Makefile.am: Run fix_python_shebang.sh after binaries are in place

- doc/xml/firewall-cmd.xml
- doc/xml/firewall-offline-cmd.xml
- src/firewall-cmd
- src/firewall-offline-cmd
FirewallD services use --set-destination to set the destination address
for a service instead of --add-destination which is used for icmptypes.
As such, fix the help messages and the related manpages.
> firewall-{,offlind}-cmd: Fix option for setting the destination address

- config/services/sip.xml
- config/services/sips.xml
This adds two new services:
- SIP (sip) on 5060/tcp and 5060/udp.
- SIP-TLS (sips) on 5061/tcp and 5061/udp.
PS: Obviously, disregard my patch sent directly via the ML earlier this week, but I suppose [this page](http://www.firewalld.org/contribute/) should be clarified.
> Adding IANA-registered sip (SIP) and sips (SIP-TLS) services (RFC3263).

- config/services/managesieve.xml
Hello
this pull request adds a service file for the ManageSieve [RFC5804] protocol.  The service file
opens port 4190 for TCP transport as described in the RFC.  It would be great to see this file
added to the project.
[RFC5804]: https://tools.ietf.org/html/rfc5804
> Add ManageSieve service

- src/firewall-cmd
Just a small correction in the help text.
> firewall-cmd: Fix typo

- src/firewall/core/fw_ifcfg.py
- src/firewall/core/fw_nm.py
The fw_ifcfg and fw_nm files are not supposed to be executed as
standalone files but rather imported by the main firewalld code so drop
the python shebangs. This also fixes a warning when building firewalld
in openSUSE OBS:
firewalld.noarch: W: non-executable-script
/usr/lib/python2.7/site-packages/firewall/core/fw_nm.py 644 /usr/bin/python
firewalld.noarch: W: non-executable-script
/usr/lib/python2.7/site-packages/firewall/core/fw_ifcfg.py 644 /usr/bin/python
> src: firewall: core: Drop unneeded python shebangs

- src/firewall/core/fw_ifcfg.py
It's possible for the ifcfg directory to be missing or named differently
so do not try to access it if it does not exist. This avoid warnings
during firewalld start up like the following one:
ERROR: Calling post func <function ifcfg_set_zone_of_interface at
0x7fb2f0d4fc80> (('', 'enp3s0')) failed: [Errno 2] No such file or
directory: '/etc/sysconfig/network-scripts'
> firewall: core: fw_ifcfg: Quickly return if ifcfg directory does not exist

- config/services/rsh.xml
My old VXWORKS boxes require RSH access for their boot and setup.  I've added the 'unencrypted' disclaimer from the telnet service to help clarify that this is not an advised service.
> Added RSH service

- config/services/high-availability.xml
Corosync is getting new daemon used as quorum network arbiter called
corosync-qnetd. This daemon is running outside of cluster and
comunication is going on tcp port 5403.
> services ha: Allow corosync-qnetd port

- doc/man/man1/Makefile.am
- firewalld.spec
This pull request add the missing firewallctl.1 manpage to the installed files and also modifies the spec file accordingly.
> firewallctl manpage

- src/firewall/core/fw_zone.py
- src/firewall/core/prog.py
In some cases, iptables commands are no longer effective.  After
starting firewalld, iptables -L, ip6tables -L are empty.
Using subprocess module to run programs instead of os.fork() fixes this
issue.  (Closes #131)
This also reduced the start and stop time for firewalld on a test
machine from 24 seconds to 4.5 seconds.  (Closes #132)
subprocess.run() is simpler to use but is only available in Python 3.5.
When a zone has some interfaces and is not the default zone, ICMP
allow/reject rules are not being set on firewalld startup.  This causes
all ICMP packets to be rejected on those zones.  Fix this by making sure
ICMP block inversion rule is always called during startup.
(Closes #130).
> Fix ICMP regression and speedup execution

- src/firewall/core/prog.py
When a command is not available, new implementation of runProg() raises
OSError which is not being handled by the callers.  Earlier
implementation returned (255, '').  Emulate earlier behavior to fix
a regression that when optional commands are not available, firewalld
fails to ignore them properly.
> Fix regression with unavailable optional commands

- src/firewall/core/fw_nm.py
If the NM module is available, instantiate the NM client when the module
is imported instead of re-instantiating in every method.
This also fixes a side-effect in firewall-applet and firewall-config
when the [connectivity] section is used in NetworkManager.conf and the
remote end pointed by the 'uri' option is unavailable. In that case,
when a NM client is started, the NetworkManager will send a
PropertiesChanged signal to notify interested subscribers that the
remote end can't be reached. However, such signals are being handled by
the nm_signal_receiver method which instantiates a new NM client because
of the nm_get_connections call. This results in another PropertiesChanged
signal to be sent again so firewall-applet and firewall-config are stuck
in an infinite loop handling the said …
> firewall: core: fw_nm: Instantiate the NM client only once

- config/services/transmission-client.xml
Added UDP protocol as both DHT and µTP are enabled in Transmission (and essential to modern-day BitTorrent) by default and they depend on UDP. 
Transmission help file says to enable both tcp and udp:
https://www.transmissionbt.com/help/gtk/2.9x/html/pfrouter.html
Removed reference to "GTK+" as there are termainl, Qt, web, and daemon variants too.
> Add UDP to transmission-client.xml service

- config/firewalld.service.in
Firewall services should be ordered before network-pre.target and should pull it, according to : https://www.freedesktop.org/wiki/Software/systemd/NetworkTarget/
This avoid any specific and fixed 'Before=' dependencies for NetworkManager and libvirtd as those services properly order themselves after network-pre.target or network.target.
> config/firewalld.service.in: use network-pre.target

- doc/xml/firewalld.richlanguage.xml
This looks like a typo of "mangle".
> Fix typo in documentation: iptables mangle table

- src/firewall/core/fw_nm.py
This actually fixes a couple of issues:
NetworkManager.service depends on firewalld.service, so that it doesn't
proceed activating services before it can set the firewall zones. That
means that fw_nm's attempt to create a NMClient always fails.
Secondly, the failure to construct a NMClient is silently discarded in
the except branch. Not cool.
Lastly, asynchronous NMClient creation could be rather expensive if
there's a lot of devices or connections. (Thankfully, it doesn't
succeed, right?). Let's not delay the service startup with it.
> firewall.core.fw_nm: create NMClient lazily

- config/services/bitcoin-rpc.xml
- config/services/bitcoin-testnet-rpc.xml
- config/services/bitcoin-testnet.xml
- config/services/bitcoin.xml
The following ports are used by bitcoin to connect to the network and provide full node capabilities.
bitcoin 8333/tcp
bitcoin-rpc 8332/tcp
The following ports are used by bitcoin to connect to the test network and provide full node capabilities.
bitcoin-testnet 18333/tcp
bitcoin-testnet-rpc 18332/tcp
> add bitcoin related services

- firewalld.spec
Commit 0ab7673fd666 ("Fix build from spec without fedorahosted.org
archives") added 'autogen.sh' to the %prep phase but this script calls
'autoreconf' so we need to add the necessary autotools dependencies to
the spec file as well.
Fixes: 0ab7673fd666 ("Fix build from spec without fedorahosted.org archives")
Signed-off-by: Markos Chandras <mchandras@suse.de>
> firewalld.spec: Add missing autotools dependencies

- config/services/ovirt-imageio.xml
Introducing ovirt's imageio service. This service is required by oVirt and will be used once migration from iptables to firewalld takes place.
> Introducing ovirt's imageio service

- doc/xml/firewall-cmd.xml
- doc/xml/firewall-offline-cmd.xml
- doc/xml/firewalld.service.xml
- doc/xml/firewalld.zone.xml
Change "protcol" to "protocol" in documentation
> Fix misspelled word in documentation

- config/services/nrpe.xml
Although the port isn't IANA registered to Nagios, it's fairly well
known (http://www.speedguide.net/port.php?port=5666).
> Adding service file for nrpe.

- config/services/murmur.xml
cf.  https://wiki.mumble.info/wiki/Running_Murmur#Settings.2C_Ports.2C_and_Authentication
for the default port
murmur availability: e.g. via the Fedora system repository
> add Murmur (Mumble server) service

- config/Makefile.am
- config/services/irc.xml
- config/services/ircs.xml
Common ports for IRC daemons are TCP 6665-6669.
> add new service IRCd

- config/Makefile.am
- config/services/nfs3.xml
This is distinct from the NFS service (v4) because it also opens up UDP
ports.
Fixes: RHBZ#1462088
> Add NFSv3 service.

- config/Makefile.am
- config/services/kprop.xml
This service is used by MIT Kerberos for KDC slave sync.
> Add kprop service

- config/Makefile.am
- config/services/git.xml
It may be helpful to have the git-daemon pre-defined as a service.  I know I'd use it.
> Add git service

- config/Makefile.am
- config/services/docker-swarm.xml
Docker swarm service allow communication between docker engines in
swarm mode.
> Add docker swarm service

- config/services/ceph.xml
Ceph has an additional daemon (ceph-mgr) that may also listen on these ports. Add this daemon to the main ceph service description.
> update description for ceph service

- config/Makefile.am
- config/services/upnp-client.xml
Important for many desktop programs, especially for home users.
This really really shouldn’t be enabled on public zones, so included
suggestion to only use it in trusted zones in the service description.
> Add new UPnP client service

- src/firewall/core/ebtables.py
- src/firewall/core/fw.py
- src/firewall/core/fw_test.py
- src/firewall/core/fw_zone.py
- src/firewall/core/ipXtables.py
Hi Eric,
This series of patches aims at improving backend abstraction in classes Firewall and FirewallZone.
For Firewall, things are pretty straightforward since it already makes use of backends internally. FirewallZone though does not, so I created a derived IPTablesFirewallZone class which holds the methods specific to iptables.
I tested each patch of the series against the testsuite on a Fedora VM.
Cheers, Phil
> Upstream queue

- config/Makefile.am
- config/services/nmea-0183.xml
GPS data service offered by GPSD, Gypsy, gps-share, etc. and used by clients like GeoClue.
Port 10110 is registered for the nmea-0183 service with IANA.
> Add nmea-0183 service

- src/firewall/core/fw.py
- src/firewall/core/watcher.py
Python3 returns the iterator for keys() instead of a list. When used dictionary is changed ( in case of firewall reload, when lost zone has been is removed ) Python3 returns error ( RuntimeError: dictionary changed size during iteration ). To fix this, list has been added, so separate copy of the keys is created and can be safely used in for loop while dictionary is being modified.
This commit also addresses issue #276
> Fixed python3 compatibility in firewall reload

- config/Makefile.am
- config/services/llmnr.xml
https://en.wikipedia.org/wiki/Link-Local_Multicast_Name_Resolution. Useful for Windows interop.
> Add llmnr service

- src/firewall-config
> firewall-config: Print error message when firewalld is not running

- src/firewall-config
The connection timer has to be reset after it's being deleted from the
timer list.
> src: firewall-config: Fix deletion of connection timer

- src/firewall-config
- src/firewall-config.glade
Some of the UI labels and headings are not marked as translatable but there is probably no good reason for that so mark them as available for translation.
> Mark some labels and headings as translatable

- src/firewall/core/logger.py
The firewalld logfile was created with the 'read' bit set for all users
which could potentially reveal information about the firewall
configuration to unauthorised users. As such, we need to make use of
the low-level I/O facilities of the 'os' module to drop that bit during
file opening and creation.
Co-Authored-By: Matthias Gerstner <matthias.gerstner@suse.com>
> core: logger: Remove world-readable bit from logfile

- configure.ac
- shell-completion/Makefile.am
- shell-completion/zsh/_firewalld
This adds a completion function for zsh to complement the existing bash function.
I expect more can be done with respect to marking mutually exclusive options. Note that in order for zsh to pick this up when compinit is run, it should be installed into /usr/share/zsh/site-functions.
A second commit on the branch is a copy/paste of the bash function installation to install the function. I'm no expert on automake and could not test this properly because I get some errors about the AM_PO_SUBDIRS macro when running autogen.sh so I'm probably missing some dependency. Feel free to squash the commits or you may want to ignore the second one.
> Add Zsh completion function

- src/tests/functions.at
This avoids triggering the following error on make check if /bin/sh is
not /bin/bash:
$ make check
make  check-local
make[1]: Verzeichnis „/home/michael/debian/build-area/firewalld-0.6.0/src/tests“ wird betreten
:;{ \
echo 'm4_define([AT_PACKAGE_NAME],[firewalld])' && \
echo 'm4_define([AT_PACKAGE_VERSION],[0.6.0])' && \
echo 'm4_define([AT_PACKAGE_STRING],[firewalld 0.6.0])' && \
echo 'm4_define([AT_PACKAGE_URL],[http://firewalld.org/])' && \
echo 'm4_define([AT_PACKAGE_BUGREPORT],[https://github.com/firewalld/firewalld])'; \
} > "package.m4"
/bin/bash ../../missing --run autom4te --language=autotest -I '.' -o testsuite.tmp testsuite.at
sh: 2: Syntax error: "(" unexpected
Fixes: #357
> tests: Remove bashism from functions.at

- config/Makefile.am
The AppStream metadata files should be placed in /usr/share/metainfo/.
Refer to https://wiki.debian.org/AppStream/Guidelines for details.
Fixes: #360
> Use preferred location for AppData files

- src/firewall/core/fw_nm.py
Hello,
As explained in #370, when using NetworkManager the automatically generated connections (such as `docker0` for the interface with the same name) make `nm_get_zone_of_connection` return False which in turn makes `firewall-config` crash.
This pull request basically changes the return values of `nm_get_zone_of_connection` so that it matches the old behavior in version 0.6.0 by returning None, except for a generated connection in which case it returns the empty string so the default zone is used by firewalld.
Let me know if this is useful.
Thanks
> firewall/core/fw_nm: nm_get_zone_of_connection return type fix

- config/Makefile.am
- config/services/spotify-sync.xml
- po/POTFILES.in
Includes a service file which opens the ports needed by the Spotify client to sync local music files with the Android (maybe iOS too?) app.
> Add Spotify local files sync service

- src/firewall/core/ipXtables.py
- src/firewall/core/nftables.py
- src/tests/regression/gh366.at
Some valid packets may be untracked and as such "ct state new" won't
match them. A prime example of this is IPv6 neighbor-advertisements. Now
adding the "icmp" service to a zone will match and accept these
untracked packets.
Note: We don't want to fully remove ct state match because we don't want
to match invalid states. This is especially important for the forward
chain.
Fixes: suse bz 1105821
> *tables: For opened ports/protocols/etc match ct state new,untracked

- config/Makefile.am
- config/services/bb.xml
- po/POTFILES.in
https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?search=1984
This port/protocol is still used by compatible monitoring systems such as Xymon. 
TCP is the primary transport layer, but UDP has been reserved for future use.
> Add Big Brother service; IANA 1984

- src/firewall-config.glade
Fix of https://github.com/firewalld/firewalld/issues/344 was incomplete, the "flags" were not translating and the reported bug was still active. I am proposing a patch which solves the issue for me.
> Fix translating labels

- src/firewall/core/io/direct.py
- src/firewall/core/io/helper.py
- src/firewall/core/io/icmptype.py
- src/firewall/core/io/ipset.py
- src/firewall/core/io/service.py
- src/firewall/core/io/zone.py
SAX is able to determine the encoding of XML files itself if the file
contains a correct "encoding" pseudo attribute, e.g.:
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
For this to work, the file stream has to be opened in binary mode, and
the parser has to read the stream using a SAX InputStream, which
autodetects the encoding.
Fix for #303.
> firewall/core/io/*.py: Let SAX handle the encoding of XML files

- src/firewall-applet.in
Previously the notification state only showed if panic mode is active or
not, while the shields up/down state is only displayed in the context
menu.
> firewall-applet: Display Shields Up/Down state in notification icon

- src/firewall/core/ipXtables.py
- src/firewall/core/nftables.py
This fixes nftables and ipXtables (when IndividualCalls=yes),
as _log_denied is not an attribute of the class but a param.
> ipXtables/nftables: Fix "object has no attribute '_log_denied'"

- .gitignore
- configure.ac
- m4/jh_path_xml_catalog.m4
m4 macro and configure check for Docbook XML stylesheets, which are
required to build firewalld.
Fixes #436
Signed-off-by: Michal Rostecki <mrostecki@suse.de>
> autoconf: Check for Docbook XML stylesheets

- doc/xml/firewall-cmd.xml.in
- doc/xml/firewall-offline-cmd.xml
Remove "this are" and fixed "succeded"
> Fix doc typo about sequence options

- src/firewall/functions.py
Firewalld runs modinfo per interesting module. With this patch it calls modinfo with multiple modules. This should lower firewalld startup time slightly.
To call get_nf_conntrack_helpers and get_nf_nat_helpers 100 times each without my patch takes:
real	0m10.087s
user	0m5.008s
sys	0m5.895s
and with my patch:
real	0m3.319s
user	0m2.621s
sys	0m0.784s
It would be possible to have only one modinfo call, but that would require to modify other modules.
> minimize modinfo calls

- firewalld.spec
Permissions on /etc/firewall were set by defattr to 644, which made the
directory inaccessible to the owner.
This causes permission problems when trying to unpack a RHEL firewalld RPM, e.g.:
```shell
firewalld-rhel7 $ rpm2cpio firewall-applet-0.6.3-1.el7.noarch.rpm | cpio -idmv     
./etc/firewall
cpio: ./etc/firewall/applet.conf: Cannot open: Permission denied
./etc/firewall/applet.conf
./etc/xdg/autostart/firewall-applet.desktop
./usr/bin/firewall-applet
./usr/share/icons/hicolor/16x16/apps/firewall-applet-error.png
./usr/share/icons/hicolor/16x16/apps/firewall-applet-panic.png
./usr/share/icons/hicolor/16x16/apps/firewall-applet.png
./usr/share/icons/hicolor/22x22/apps/firewall-applet-error.png
./usr/share/icons/hicolor/22x22/apps/firewall-applet-panic.png …
```
> Fix permissions of the /etc/firewall directory

- config/Makefile.am
This is supported since dbus 1.9.18.
The old location in /etc/dbus-1/system.d/ has been deprecated.
https://lists.freedesktop.org/archives/dbus/2015-July/016746.html
> Move D-Bus policy file to /usr/share/dbus-1/system.d/

- config/Makefile.am
- doc/xml/Makefile.am
- doc/xml/firewall-cmd.xml.in
- doc/xml/firewalld.xml.in
This patch fixes two problems when you try to build outside the source
tree, as in:
mkdir build
cd build
../configure
> fix building in a separate directory outside the source tree

- src/firewall/core/rich.py
I found out I did not set a value for invert when adding the rich rule via firewall-cmd. Then I got the error as mentioned in issue #457 because the invert attribute was given a default value None. I corrected it here so that it gets the default value False. This fixed the issue for me.
> fix issue #457

- src/firewall/core/ipXtables.py
We are looking to compare the type, not the object.
Without this fix ipXtables will only mark the very first packet of a connection.
Signed-off-by: Felix Kaechele <heffer@fedoraproject.org>
> Fix Rich_Mark logic

- config/Makefile.am
- config/services/freeipa-4.xml
- config/services/freeipa-ldap.xml
- config/services/freeipa-ldaps.xml
- config/services/freeipa-replication.xml
- po/POTFILES.in
The firewall services ``freeipa-ldap``, ``freeipa-ldaps``, and
``freeipa-replication`` are outdated. FreeIPA 4.x requires a different set
of rules.
* Port 7389 and service ``freeipa-replication`` are no longer needed since
RHEL 7.0 and Fedora 18. Port 7389/TCP was used for Dogtag's LDAP server.
FreeIPA 3.1 consolidated the 389-DS databases and now Dogtag and IPA
share the same LDAP server instance.
* FreeIPA requires both LDAP and LDAPS to work properly. Iit doesn't make
any sense to have separate services ``freeipa-ldap`` and
``freeipa-ldaps``. FreeIPA clients and master-master replication both
require port 389/TCP (LDAP) to work. The LDAP protocol is not a security
problem, because FreeIPA doesn't use plaintext LDAP but STARTTLS and/or
GSSAPI to authenticate and protect. Dogtag PKI also …
> Add firewall rules for FreeIPA 4.x

- config/Makefile.am
- config/services/bittorrent-lsd.xml
- po/POTFILES.in
This adds a service for [Local Peer Discovery](https://en.wikipedia.org/wiki/Local_Peer_Discovery).
The acronym is LSD because the official name is [Local Service Discovery](http://bittorrent.org/beps/bep_0014.html), but AFAIK no BitTorrent client calls it that.
> Add BitTorrent Local Peer Discovery service

- config/services/RH-Satellite-6.xml
For well known ports/services, use service includes instead of the
explicit port number.
> chore: config/services/RH-Satellite-6: use service includes

- config/services/freeipa-4.xml
For well known ports/services, use service includes instead of the
explicit port number.
> chore: config/services/freeipa-4: use service includes

- doc/xml/firewall-cmd.xml.in
- src/firewall-cmd.in
This is a documentation change to reflect that `--change-interface` option can indeed be used together with  `--permanent` option.
Fixes #479
> Change-interface can accept permanent option

- config/services/matrix.xml
For well known ports/services, use service includes instead of the
explicit port number.
> config/services/matrix: use service include

- config/services/tftp.xml
TFTP service description has a typo; "from a remote machine in **s** simple way".
> Fix typo in TFTP service description

- doc/xml/firewall-config.xml
Very minor typo in `firewall-config(1)`
> Typo in firewall-config(1)

- .github/semantic.yml
We now enforce using conventional commits. This config requires every
commit to use the convention and disallows merge commits. This follows
our typical "rebase and merge" strategy.
> improvement(github): add config for Semantic Pull Requests app

- src/firewall/core/fw_zone.py
Currently its broken:
```
Traceback (most recent call last):
File "/usr/lib/python3.8/site-packages/firewall/server/decorators.py", line 53, in handle_exceptions
return func(*args, **kwargs)
File "/usr/lib/python3.8/site-packages/firewall/server/firewalld.py", line 93, in start
return self.fw.start()
File "/usr/lib/python3.8/site-packages/firewall/core/fw.py", line 478, in start
self._start()
File "/usr/lib/python3.8/site-packages/firewall/core/fw.py", line 443, in _start
self.zone.apply_zones(use_transaction=transaction)
File "/usr/lib/python3.8/site-packages/firewall/core/fw_zone.py", line 169, in apply_zones
self.apply_zone_settings(zone, use_transaction=use_transaction)
File "/usr/lib/python3.8/site-packages/firewall/core/fw_zone.py", line 286, in apply_zone_settings …
```
> Fix handling of <forward/> tag in zone definitions

- .travis.yml
- src/firewall/core/fw_ipset.py
- src/tests/cli/firewall-cmd.at
- src/tests/dbus/firewalld.conf.at
- src/tests/functions.at
- src/tests/regression/gh509.at
- src/tests/regression/rhbz1779835.at
Re-enables running the testsuite in travis-ci. Because Bionic has too old a kernel the nftables tests must run with IndividualCalls=yes. This is due to the kernel missing support for NFTA_RULE_POSITION_ID which was added in kernel 5.1.
@todoleza, you may find this PR interesting. It required a few test fix ups.
> renable travis-ci tests

- src/firewall-offline-cmd.in
All commands are permanent. The "[P]" tag is unnecessary.
> fix(firewall-offline-cmd): remove instances of "[P]" in help text

- config/services/freeipa-trust.xml
Samba did change DCE RPC dynamic port range to 49152-65535 with version 4.7.
Signed-off-by: Alexander Bokovoy <abokovoy@redhat.com>
> freeipa-trust: update dynamic DCE RPC ports

- src/firewall/client.py
- src/tests/python/firewalld_config.py
The new setZoneSettings2 D-Bus method was not handling a few zone
attributes which are plain attributes and do not have add/remove
methods: version, short, description, and target.
The problem was most evident with the client setZoneSettings method,
which was feeding back the complete zone settings, which was failing
like this:
Traceback (most recent call last):
File "src/firewall/server/decorators.py", line 67, in dbus_handle_exceptions
return func(*args, **kwargs)
File "src/firewall/server/firewalld.py", line 917, in setZoneSettings2
self.fw.zone.set_config_with_settings_dict(zone, settings, sender)
File "src/firewall/core/fw_zone.py", line 398, in set_config_with_settings_dict
raise FirewallError(errors.INVALID_SETTING, "Unhandled setting type {} key {}".format(type(settings[key]), …
> fix(dbus): handle all zone settings in setZoneSettings2 method

- src/firewall/command.py
Unify indentation for forward-ports and rich rules in the CLI zone listing.
Do not insert redundant newlines and tabulation if there are no forward-ports or rich rules.
Actual results (currently):
```
$ sudo firewall-cmd --list-all-zones
...
external (active)
target: default
icmp-block-inversion: no
interfaces: 
sources: 
services: ssh
ports: 
protocols: 
masquerade: yes
forward-ports: port=22:proto=tcp:toport=:toaddr=192.168.2.3
port=80:proto=tcp:toport=:toaddr=192.168.2.3
source-ports: 
icmp-blocks: 
rich rules: 
rule protocol value="ipv6-icmp" accept
rule priority="32767" reject
...
```
Expected results (after the patch):
```
$ sudo firewall-cmd --list-all-zones
...
external (active)
target: ACCEPT
icmp-block-inversion: no
interfaces: 
sources: 
services: ssh
ports: 
protocols: …
```
> fix(cli): unify indentation for forward-ports and rich rules

- config/services/ipsec.xml
IKE and IPsec over TCP is defined in RFC 8229. It specifically mentions
no ports to allow administrators to configure any port to prevent being
blocked by networks.
However, most IKE/IPsec blocking seems to come from unwanted accidental
UDP blocks, so any TCP would usually ensures IPsec can still work on
such networks. The default is therefor to pick the same TCP port as IKE
and IPsec over UDP uses, port 4500.
> improvement(service): IPsec: Update description and add TCP port 4500

- src/firewall/core/rich.py
- src/tests/regression/rhbz1689429.at
Fixes: 3a0e79b1cfe4 ("fix: core: rich: Catch ValueError on non-numeric priority values")
> fix(rich): use correct error code for invalid priority

- doc/xml/firewalld.dbus.xml
Replace invalid method names for both 'queryEntry' and 'queryIPSet'.
fixes #693
> docs(dbus): fix invalid method names.

- config/Makefile.am
- config/services/kube-api.xml
- config/services/kube-control-plane.xml
- config/services/kube-controller-manager.xml
- config/services/kube-scheduler.xml
- config/services/kubelet-worker.xml
- po/POTFILES.in
Based on the ports list from: https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/
This adds some static services for the individual components and two "meta services".
Someone following the guide there can open the required ports on the master/control plane with `kube-master` and on the worker/nodes with `kubelet-worker`.
I'm not 100% happy with the names for the "meta services" but master and worker seemed to fit along with the possibility that workers may add more services than just `kubelet` down the road.
> Add Kubernetes definitions

- src/firewall/core/ipXtables.py
- src/firewall/core/nftables.py
- src/tests/features/rfc3964_ipv4.at
Now that policies allow filtering on the OUTPUT we must also generically
accept established connections in OUTPUT. Otherwise a policy that blocks
all OUTPUT will cause even selectively allowed traffic to drop. This is
because "allows" match on "ct state new", which only matches on the
_first_ packet.
Fixes: #705
> fix(policy): generic accept of established connections in OUTPUT

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/enhancement.md
These issue templates will be useful for people wanting to make bug reports and feature requests, so they know how much information is needed, and it's helpful for developers to more easily replicate bugs.
> docs: Add issue templates for bug fixes and feature requests

- src/firewall/functions.py
Generating the table was taking an unreasonable amount of memory.
Stripping C0 and C1 should cover most scenarios while limiting memory
usage.
Fixes: ac5960856991 ("fix(rich): non-printable characters removed from rich rules")
> fix(rich): limit table to strip non-printables to C0 and C1

- .github/workflows/testsuite.yml
- src/tests/functions.at
The testsuite often catches regressions in nftables. Lets always run
against nftables master to catch regression earlier.
> ci: add nftables-master to test matrix

- README
- firewalld.spec
- src/firewall/client.py
- src/firewall/server/decorators.py
Modern python has functools.wraps() which is sufficient. One less
dependency.
Fixes: rhbz 1944206
> chore: drop dependency on python-decorator

- config/Makefile.am
- config/services/wireguard.xml
- po/POTFILES.in
Of course, one can set up wireguard to listen on any other port.
However, 51820 is a good default that is used in many places.
> feat(service): Add WireGuard service definition

- src/firewall-applet.in
Removes the HTML markup tags in the Qt applet tooltip, as they cannot be rendered in KDE now and will produce garbled output.
Seems that other projects are also resolving this problem similarly by removing the HTML tags. 
See https://github.com/clementine-player/Clementine/pull/6745 and https://github.com/qbittorrent/qBittorrent/commit/89277a2f52b2bcade3798f85f262dc4e9724667c
Related discussions in KDE community can be found at: https://bugs.kde.org/show_bug.cgi?id=422616
Resolves #668 
Resolves #701
> fix(applet): Show a basic tooltip instead of HTML in system tray

- config/services/syncthing.xml
Syncthing also accepts UDP based QUIC connections on port 22000.
> improvement(service): Syncthing add UDP port 22000

- .github/workflows/source-checks.yml
- .github/workflows/testsuite.yml
- README
- firewalld.spec
- po/POTFILES.in
- src/Makefile.am
- src/firewall-applet.in
- src/firewall/client.py
- src/firewall/server/config.py
- src/firewall/server/config_helper.py
- src/firewall/server/config_icmptype.py
- src/firewall/server/config_ipset.py
- src/firewall/server/config_policy.py
- src/firewall/server/config_service.py
- src/firewall/server/config_zone.py
- src/firewall/server/dbus.py
- src/firewall/server/decorators.py
- src/firewall/server/firewalld.py
- src/firewall/server/server.py
- src/tests/Makefile.am
- src/tests/functions.at
- src/tests/integration/dbus.at
- src/tests/integration/dbus_auth_uid.at
- src/tests/integration/polkit.at
- src/tests/integration/polkit_auth_desktop.at
- src/tests/integration/polkit_auth_server.at
- src/tests/integration/polkit_restart.at
- src/tests/integration/testsuite.at
This drops the dependency on `python-slip`. Policy Kit authorization is now done via a custom decorator.
> drop dependency python-slip

- doc/xml/policy_zone_descriptions.xml
Fixes: 4095551e2679 ("Fixed usage: direct options are not related to zones, addes missing direct options, fixed ports in forward-port entry.")
> docs(zone): fix remaining usage of --list={services,icpmtypes}

- firewalld.spec
- src/tests/Makefile.am
- src/tests/README
- src/tests/functions.at
- src/tests/python/python.at
Install the testsuite. This will make it easier for end users to verify
they have a sane environment for firewalld. Users often build custom
kernels which may be missing features firewalld relies upon.
--->8---
New RPM subpackage: firewalld-test
New files:
```
[root@vm-bos-rhel8-1 testsuite]# find /usr/share/firewalld/testsuite/
/usr/share/firewalld/testsuite/
/usr/share/firewalld/testsuite/README
/usr/share/firewalld/testsuite/testsuite
/usr/share/firewalld/testsuite/integration
/usr/share/firewalld/testsuite/integration/testsuite
/usr/share/firewalld/testsuite/python
/usr/share/firewalld/testsuite/python/firewalld_config.py
/usr/share/firewalld/testsuite/python/firewalld_direct.py
/usr/share/firewalld/testsuite/python/firewalld_rich.py …
```
> improvement(testsuite): install to $(pkgdatadir)/testsuite

- .github/semantic.yml
- doc/xml/firewall-cmd.xml.in
- doc/xml/firewall-offline-cmd.xml
Fixes: rhbz 1899933
Fixes: rhbz 1975484
> doc(firewall-*cmd): client conntrack helpers must use a policy

- src/firewall/core/ipXtables.py
- src/firewall/core/nftables.py
- src/tests/cli/firewall-cmd.at
- src/tests/features/rfc3964_ipv4.at
- src/tests/features/rpfilter.at
- src/tests/features/zone.at
- src/tests/regression/gh258.at
- src/tests/regression/rhbz1514043.at
Since f2896e43c3a5 ("fix(zone): target: default is now similar to
reject") zones are fully terminal. They always end in an
accept/drop/reject. As a result policies with a priority >0 are not
actually reachable. The dispatch happens _after_ the zone's chains.
The solution is to jump to the policy dispatch just before the catch-all
accept/drop/reject in the zone. Since we're doing that we might as well
move the < 0 policy dispatch into the zone chains for uniformity. The
latter has no functional difference.
The exception is the OUTPUT chains. They don't have zone dispatch so the
top level jump to policy dispatch is retained.
Fixes: f2896e43c3a5 ("fix(zone): target: default is now similar to reject")
> fix(policy): unreachable when priority > 0

- config/macros.firewalld
While unlikely, we cannot exactly predict how a running system has its
permissions set, but we can guard against it to prevent weird failures.
This should have no appreciable impact, but ensures that we do not try
to run `firewall-cmd` if it is not actually executable.
> fix(config): Fix RPM macros to test if firewall-cmd is executable

- config/Makefile.am
- config/services/llmnr-tcp.xml
- config/services/llmnr-udp.xml
- po/POTFILES.in
TCP implementation cannot work with destination addresses.
> improvement(service): LLMNR: split into llmnr-tcp and llmnr-udp

- src/tests/cli/firewall-cmd.at
- src/tests/features/icmp_blocks.at
- src/tests/features/rfc3964_ipv4.at
- src/tests/features/rich_rules.at
- src/tests/features/zone.at
- src/tests/functions.at
- src/tests/regression/gh258.at
- src/tests/regression/icmp_block_in_forward_chain.at
- src/tests/regression/rhbz1514043.at
- src/tests/regression/rhbz1855140.at
Since nftables commit d0f3b9eaab8d ("payload: auto-remove simple
icmp/icmpv6 dependency expressions") the ICMP output may remove
dependencies. As such normalize the output to be compatible with old and
new versions.
> test(functions): nft: normalize ICMP type output

- src/firewalld.in
If dropping capabilities is blocked by SELinux, e.g. old selinux-policy,
then capng_apply() will return non-zero. Also check other things that
may fail, i.e. capng_update().
Fixes: rhbz 1999090
> fix(firewalld): check capng_apply() return code

- doc/xml/firewalld.policy.xml
A typo in manpage causes following content in keys description:
`target="CONTINUEACCEPT|REJECT|DROP"`
> docs(policy): fix typo in 'target' values

- doc/xml/firewalld.policies.xml
This commit fixes typo in ``firewalld-policies`` man page.
> docs(policies): fix typos

- src/firewall/core/ipset.py
- src/tests/regression/gh881.at
This makes the complexity linear by sorting the networks ahead of time.
Fixes: #881
Fixes: rhbz2043289
> fix(ipset): further reduce cost of entry overlap detection

- doc/xml/policy_zone_descriptions.xml
- doc/xml/policy_zone_syntax.xml
Add missing `mac` and `ipset` attributes.
source of information: `firewalld.richlanguage.xml`
> docs(policy): update documentation for rule "source" and "destination" elements

- doc/xml/policy_zone_descriptions.xml
- doc/xml/policy_zone_syntax.xml
Fix minor syntax error for `log` element too.
source of information: `firewalld.richlanguage.xml`
> docs(policy): add missing "nflog" documentation for rule

- doc/xml/firewall-cmd.xml.in
- doc/xml/firewall-offline-cmd.xml
- doc/xml/firewalld.dbus.xml
- doc/xml/firewalld.direct.xml
Spotted by lintian:
```
I: firewalld: typo-in-manual-page usr/share/man/man1/firewall-cmd.1.gz line 1300 wether whether
N:
I: firewalld: typo-in-manual-page usr/share/man/man1/firewall-cmd.1.gz line 1320 wether whether
N:
I: firewalld: typo-in-manual-page usr/share/man/man1/firewall-cmd.1.gz line 1340 wether whether
N:
I: firewalld: typo-in-manual-page usr/share/man/man1/firewall-cmd.1.gz line 1360 wether whether
N:
I: firewalld: typo-in-manual-page usr/share/man/man1/firewall-cmd.1.gz line 1380 wether whether
N:
I: firewalld: typo-in-manual-page usr/share/man/man1/firewall-cmd.1.gz line 1478 wether whether
N:
I: firewalld: typo-in-manual-page usr/share/man/man1/firewall-offline-cmd.1.gz line 1168 wether whether
N:
I: firewalld: typo-in-manual-page …
```
> typo fixes

- config/Makefile.am
- config/services/gpsd.xml
- po/POTFILES.in
[gpsd](https://gpsd.io/) is a service daemon that monitors one or more GPSes or AIS receivers attached to a host computer through serial or USB ports, making all data on the location/course/velocity of the sensors available to be queried on TCP port 2947 of the host computer.
> add gpsd-server service

- doc/xml/firewall-cmd.xml.in
- doc/xml/firewall-offline-cmd.xml
The value type should be target rather than zone
> docs(firewall-cmd): fix typo in set-target option

- config/firewalld.service.in
This avoids a dependency loop with cloud-init and other early boot
services.
The alternative is to also become an early boot service by using
`DefaultDependencies=no`, but that would mean changes inside of firewalld
to handle dbus not being available.
Fixes: #414
> fix(systemd): order Before network.target

- doc/xml/firewalld.dbus.xml
> docs(dbus): Fix invalid ipset method name

- src/tests/regression/rhbz1871298.at
On some low performance devices (ARM Cortex A35) this test needs much
longer.
> test: rich rule parsing bottleneck increase timeout

- config/Makefile.am
- config/services/cratedb.xml
- po/POTFILES.in
Open tcp ports 4200, 4300 and 5432 for CrateDB service.
> feat(service): Add CrateDB ports

- config/Makefile.am
- config/services/prometheus-node-exporter.xml
- po/POTFILES.in
Add prometheus node-exporter service definition for default port 9100
> Prometheus node-exporter

- configure.ac
- doc/xml/firewalld.xml.in
- src/firewall/config/__init__.py.in
- src/firewalld.in
This adds a new parameter to firewalld: --log-target. It allows to configure firewalld to send log messages to only one output channel. I think this allows a much better integration with systemd journald and simplifies the usage in general.
Requiring logrotate on a systemd machine seems like a drawback to me.
Generating log messages and redirecting them to /dev/null looks more like a workaround than a great design.
> Simplify logging

- src/tests/functions.at
On Debian derived systems, /bin/sh points to dash and not bash.
This leads to the following lintian error:
```
E: firewalld-tests: shell-script-fails-syntax-check [usr/share/firewalld/testsuite/integration/testsuite]
N:
N:   Running this shell script with the shell's -n option set fails, which means that the script has syntax errors.
N:   The most common cause of this problem is a script expecting /bin/sh to be bash checked on a system using dash as
N:   /bin/sh.
N:
N:   Run e.g. sh -n yourscript to see the errors yourself.
N:
N:   Note this can have false-positives, for an example with bash scripts using "extglob".
N:
N:   Visibility: error
N:   Show-Always: no
N:   Check: script/syntax
N:
N:
E: firewalld-tests: shell-script-fails-syntax-check [usr/share/firewalld/testsuite/testsuite] …
```
> tests/functions: Remove bashism

- config/Makefile.am
- config/services/bareos-director.xml
- config/services/bareos-filedaemon.xml
- config/services/bareos-storage.xml
- po/POTFILES.in
- Add bareos-director (bareos-dir) service definition for default port 9101.
- Add bareos-filedaemon (bareos-fd) service definition for default port 9102.
- Add bareos-storage (bareos-sd) service definition for default port 9103.
Signed-off-by: Bruno Friedmann <bruno.friedmann@bareos.com>
> feat(service): add bareos-director bareos-filedaemon bareos-storage

- shell-completion/bash/firewall-cmd
Fix typo that prevent autocompletion of --ipset commands.
> fix(bash): fix ipset commands autocompletion

- config/Makefile.am
- config/services/ceph-exporter.xml
- po/POTFILES.in
Add Prometheus module listening on default port 9283.
(https://docs.ceph.com/en/quincy/mgr/prometheus/)
> feat(service): add Ceph Prometheus exporter

- src/firewall/core/modules.py
Don't error if /proc/modules is missing.
This is a fix for #1000 
Not extensively tested, but works well for me.
I'm not aware of why a kernel module would need to be unloaded.   This can't happen on non-modular kernels.  Without being aware of the reason why firewalld attempts to unload kernel modules, I can't comment on what effects the non-unloading of them will have.
> Fix for firewalld running on systems with non-modular kernels

- .github/workflows/release.yml
- Makefile.am
This will create a new release with generated release notes and distribution tarball.
The goal is to use PRs to do the backports and spec file version bump. Then trigger the release with by manually pushing a tag based on that PR. If this works well, then in the future we could consider letting the gh action also create the tag.
> ci: automatic releases on tag push

- src/tests/functions.at
As noted in issue #1051, using only redirections inside $(command) is unspecified.
As per [POSIX][1]:
With the $(command) form, all characters following the open
parenthesis to the matching closing parenthesis constitute the
command. Any valid shell script can be used for command, except a
script consisting solely of redirections which produces unspecified
results.
[1]: https://pubs.opengroup.org/onlinepubs/9699919799.2018edition/
> test: functions: command substitution cannot use only redirections

- config/Makefile.am
- config/services/jellyfin.xml
- po/POTFILES.in
This reverts commit 8c168d9eda5fd035d91422393ffea9b6ebcd2728.
As reported in https://github.com/jellyfin/jellyfin/issues/8587, this causes an issue with RPMs shipped by Jellyfin. This has been reported to firewalld in https://github.com/firewalld/firewalld/issues/1057, where @joshuaboniface stated that the Jellyfin project would like to remove the Jellyfin config from firewalld, which is what this change does.
CC: @erig0
> Revert "feat(service): Add jellyfin service"

- src/firewall/core/ipXtables.py
- src/firewall/core/nftables.py
Remove duplicate rich rule fragments and assign default value to chain suffix variable.
Also directly return concatenated rule fragments.
> fix(tcp-mss-clamp): duplicate rule fragments

- config/Makefile.am
- config/services/zabbix-agent.xml
- config/services/zabbix-java-gateway.xml
- config/services/zabbix-server.xml
- config/services/zabbix-trapper.xml
- config/services/zabbix-web-service.xml
- po/POTFILES.in
We at Zabbix had a feature request filed ([ZBXNEXT-4737](https://support.zabbix.com/browse/ZBXNEXT-4737)) that requested we add `firewalld` configurations for networking Zabbix components.
In the course of discussion, we became aware that `firewalld` included configurations for Zabbix components [5 years ago](https://github.com/firewalld/firewalld/commit/bbf127bde23da98eae2697a3db6abdaa5a96fbb7), and after reviewing them, decided to contribute an update to them, hence this PR.
The gist of changes can be summarised as follows:
* a configuration for the Zabbix Java Gateway component was added ([zabbix-java-gateway.xml](https://github.com/firewalld/firewalld/compare/master...jxlambda:firewalld:master#diff-92c8d4f018bdd935586d4dbd54e27f134a1f42965cdd8cf90a0f3e9b6e175e4f))
* the …
> Update to Zabbix port configurations

- config/Makefile.am
- config/services/opentelemetry.xml
- po/POTFILES.in
Open Telemetry is a useful tool for collecting a bunch of system data and shipping it off for analysis.
> feat(service): add OTLP service

- src/firewall-applet.in
Fixed: https://github.com/firewalld/firewalld/issues/315
Firewall-applet allows to open KDE network connection editor.
> #315 - Firewall-applet allows to use KDE network connection editor

- src/firewall/core/fw_nm.py
The glue layer between FirewallD and NetworkManager uses what NM calls "IP interface" names to identify interfaces. However, these names can't be passed to NM.Client.get_device_by_iface() since that checks the "interface name", not the IP interface name. Since NM does not provide a method to look up a device by its IP interface, we need to do that manually.
Fixes: #878
> fix(fw_nm): use IP interface names for connection lookup

- .github/workflows/integration-testsuite.yml
- .github/workflows/testsuite.yml
Disable python in the nftables build since we're going to install it via pip.
> ci(github): fix pip install permission issue

- config/Makefile.am
- config/services/syscomlan.xml
- po/POTFILES.in
Port 1065 is registered to syscomlan at IANA.  I'll confess I don't totally understand what it is for, but one of our local applications is using this port so I figured I'd share.
> feat(service) Add syscomlan

- src/firewall-applet.in
QtWidgets.QSystemTrayIcon.Trigger was moved to QtWidgets.QSystemTrayIcon.ActivationReason.Trigger in qt6
> fix(applet): ActivationReason.Trigger

- src/firewall/functions.py
- src/tests/python/firewalld_config.py
- src/tests/python/firewalld_direct.py
- src/tests/python/firewalld_test.py
Avoid warnings:
```
src/tests/python/firewalld_test.py::TestFirewallD::test_zone_add_get_query_removeForwardPort
/data/src/firewalld/src/tests/python/firewalld_test.py:226: DeprecationWarning: Please use assertRaisesRegex instead.
self.assertRaisesRegexp(Exception, 'ALREADY_ENABLED', self.fw_zone.addForwardPort, zone, port, protocol, toport, toaddr, 0)
```
unittest.TestCase.assertRaisesRegexp is deprecated for assertRaisesRegex since Python 3.2. It exists since Python 3.1. Even CentOS Linux 8 brings Python 3.6.
- https://docs.python.org/3.3/library/unittest.html#unittest.TestCase.assertRaisesRegex
- https://bugs.python.org/issue10273
> fix(tests): avoid deprecated assertRaisesRegexp for assertRaisesRegex

- src/firewall/core/icmp.py
This was only called from IPSet.check_entry() to validate the input. Also, some of the IPv4 names are the same as for IPv6. Overall, the impact of this was probably low.
Fixes: 11567b74317e ('New firewall.core.icmp providing names and types for icmp and icmpv6 values')
> fix(icmp): fix check_icmpv6_name() to use correct IPv6 names

- doc/xml/firewalld.lockdown-whitelist.xml
Bug-Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1040547
> docs: fix reference to lockdown-whitelist.xml in SYNOPSIS section

- src/firewall/core/nftables.py
- src/tests/cli/firewall-cmd.at
Setting an IP range with nftables did not work:
```bash
firewall-cmd --permanent --delete-ipset=testipset || :
firewall-cmd --permanent --delete-zone=testzone || :
ENTRY=1.1.1.1-1.1.1.10
firewall-cmd --permanent --new-ipset=testipset --type=hash:ip
firewall-cmd --permanent --ipset=testipset --add-entry="$ENTRY"
firewall-cmd --permanent --info-ipset=testipset
firewall-cmd --permanent --new-zone=testzone
firewall-cmd --permanent --zone=testzone --add-rich-rule='rule family="ipv4" source ipset="testipset" service name="ssh" accept'
firewall-cmd --reload &
```
This would generate the following JSON request:
```json
{
"add": {
"element": {
"family": "inet",
"table": "firewalld",
"name": "testipset",
"elem": [
"1.1.1.1-1.1.1.10"
]
}
}
}
```
libnftables will try to resolve "1.1.1.1-1.1.1.10" via …
> fix(ipset): fix configuring IP range for ipsets with nftables

- firewalld.spec
Instead of Requires. iptables, et al. have been optional for a long time. The spec file should reflect that.
> chore(rpm): Recommend iptables et al.

- .gitignore
Running `ctags -R .` is useful for firewalld, to get some basic indexing of the python functions.
Ignore the resulting "tags" file.
> improvement(build): add ctags' "tags" file to `.gitignore`

- README.md
It's not clear which is the minimally supported/required Python version. Document it. Pick 3.6, because that version is in Centos7 and contains a lot of API that we may want to rely on.
Optimally, we would have CI tests that check the minimum version. I think currently we don't test Python 3.6.
> improvement(doc): list required Python version in "README.md"

- .flake8
- Makefile.am
- src/Makefile.am
- src/firewall-config.in
- src/firewall/core/ebtables.py
- src/firewall/core/fw_policy.py
- src/firewall/core/fw_zone.py
- src/firewall/core/io/policy.py
- src/firewall/core/ipXtables.py
- src/firewall/core/nftables.py
- src/firewall/core/rich.py
- src/firewall/fw_types.py
add a `.flake8` config file. This allows to run plain `flake8` in our source tree, and it does the right thing.
Also, drop a few errors from the ignore list, which don't produce any failures (anymore).
> add `.flake8` configuration file to ignore errors

- src/firewall/core/nftables.py
- src/tests/regression/rhbz1506742.at
With
```bash
firewall-cmd --permanent --delete-ipset=testipset || :
firewall-cmd --permanent --new-ipset=testipset --type=hash:ip --option=maxelem=65536 --option=family=inet --option=hashsize=4096 --option=timeout=14400
firewall-cmd --reload
```
firewalld would send the JSON request
```json
{
"add": {
"set": {
"family": "inet",
"table": "firewalld",
"name": "testipset",
"type": "ipv4_addr",
"flags": [
"interval"
],
"timeout": "14400",
"size": "65536"
}
}
},
```
But the "timeout","size" keys are NUMBER types in libnftables-json. They are silently ignored otherwise ([1]). The fix is to pass them as numbers.
Try also:
```bash
nft delete table inet testtable &>/dev/null || :
nft add table inet testtable
echo '
{
"nftables": [
{
"metainfo": {
"json_schema_version": 1
}
},
{
"add": {
"set": { …
```
> fix(ipset): fix configuring "timeout","maxelem" values for ipsets with nftables

- Makefile.am
- config/firewall-config.appdata.xml.in
The default firewalld branch will be renamed from "master" to "main". This is part of the conscious language effort. Many projects did such a change, and with time, "main" is (becoming?) the most popular name for the default branch.
There are little actual changes necessary, except pushing the "main" branch, deleting the "master" branch and fixing a bit of fall-out.
This commit changes a few references of "master" in the source tree.
See-also: https://github.com/github/renaming/#renaming-the-default-branch-from-master
> improvement(build): rename the "master" branch to "main"

- README.md
- config/Makefile.am
- config/services/cratedb.xml
- config/services/minidlna.xml
- config/services/plex.xml
- config/tests/policies/libvirt-routed-in.xml
- config/tests/policies/libvirt-routed-out.xml
- config/tests/policies/libvirt-to-host.xml
- config/tests/zones/FedoraServer.xml
- config/tests/zones/FedoraWorkstation.xml
- config/tests/zones/libvirt-routed.xml
- config/tests/zones/libvirt.xml
- config/tests/zones/nm-shared.xml
- config/xmlschema/check.sh
- config/xmlschema/helper.xsd
- config/xmlschema/icmptype.xsd
- config/xmlschema/ipset.xsd
- config/xmlschema/policy.xsd
- config/xmlschema/service.xsd
- config/xmlschema/zone.xsd
- firewalld.spec
While firewalld command line tools now have an option `--check-config`,
it's still useful to have a scheme for our XML files.
Revert the removal of the XSD schemas.
This replaces/obsoletes pull request [1], because I think we should
restore the previous schema, instead of writing a new one.
This reverts the removal from commit 81d3d6a7d84bc34a18ddd4ab6153f0dafb2fa17e.
[1] https://github.com/firewalld/firewalld/pull/492
Fixes: https://github.com/firewalld/firewalld/issues/488
> [th/xml-schema] restore XSD XML schemas for validating config files

- config/Makefile.am
- config/services/smtp-submission.xml
- config/services/submission.xml
- po/POTFILES.in
* This commit adds the correct service name for SMTP mail submission for clients/users using tcp/587 and udp/587 ports.
* It resolves the naming confusion between the service name on firewalld and the defaults on `/etc/services`:
https://access.redhat.com/articles/1761
* It adheres to the defined rules in RFC6409, which can be on: https://www.rfc-editor.org/rfc/rfc6409.html
* It aligns with the service name and port reservations listed by IANA:
https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?&page=11
This PR does not removes the misleading `smtp-submission` service name to avoid breaking already existing software that relies on the old service name.
> Add submission service for SMTP over port 587

- src/firewall/core/nftables.py
Preface: I'm not a Python expert, so I'm hoping you can test to make sure my suggestions are not breaking something. My tests produced identical JSON output, but my tests are not exhaustive.
This one instance of deepcopy() uses 85% of the processing time and deepcopy() is about 15 times slows than marshal in my tests.
Switch `_deduplicated_rules` from a list to a dict and use the rule_key as the key. Avoids another call to `_get_rule_key()` and avoids duplicating rules.
```diff
-        for rule in _deduplicated_rules:
+        for rule_key in _deduplicated_rules:
index += 1  # +1 due to metainfo
-            rule_key = self._get_rule_key(rule)
+            rule = _deduplicated_rules[rule_key]
```
Pre-calculate ipset information and pass it through build_set_add_rules()
```diff
-    def …
```
> Performance: nftables reload

- .git-blame-ignore-revs
If you want to use git-blame and are bothered by the large diff due to the reformatting with python-black, consider ignoring the reformatting commit by using ".git-blame-ignore-revs" file.
---
this is a follow-up to the reformatting with python black.
The `.git-blame-ignore-revs` file contains a comment that explains how to use it (or its purpose).
> improvement(build): add ".git-blame-ignore-revs" file for "blame.ignoreRevsFile" git config

- src/firewall/core/fw_nm.py
After the reload command is executed, a large number of routes are added, which increases the memory usage of firewalld. This may not be caused by firewalld. However, firewalld is affected by this. It is recommended that the nmclient be released after the reload is complete.
> clean up the created nmclient when the reload is complete

- src/tests/python/firewalld_config.py
Python-3.12 removed unittest.assertEquals() [1].
[1]: https://docs.python.org/dev/whatsnew/3.12.html#id3
> test(python): compatibility with python-3.12

- contrib/fw-in-container/fw-in-container
- fix list of installed packages. Some package names were wrong. Either they didn't exist (and shouldn't be installed), or there was a typo.
- export "TERM=xterm". Otherwise, it defaults to "dump", which prevents pagers from working properly.
> [th/fw-in-container-adjustment] fw-in-container: minor improvements to container script

- src/firewall-config.in
```
$ flake8
<unknown>:1876: SyntaxWarning: invalid escape sequence '\s'
./src/firewall-config.in:1876:36: W605 invalid escape sequence '\s'
```
Fixes: d81485cdf4c1 ('improvement(firewall-config): show zone description as tooltip')
> [th/python-inval-escape-seq] fix(firewall-config): fix invalid escape sequence in Python source for regex

- src/firewall/core/io/policy.py
- src/tests/features/rich_rules.at
Previously, validation of valid service names was not done. That meant:
```
$ firewall-cmd --add-rich-rule='rule priority="-100" family="ipv4" source address="10.0.0.10" service name="listen" accept' --permanent
success
$ firewall-cmd --reload
Error: INVALID_SERVICE: listen
```
which left firewalld in a bad state.
Now:
```
$ firewall-cmd --add-rich-rule='rule priority="-100" family="ipv4" source address="10.0.0.10" service name="listen" accept' --permanent
Error: INVALID_SERVICE: Zone 'public': 'listen' not among existing services
```
It's still not all golden. If you now have to happen an XML file with an unknown service on disk, on restart we get tracebacks and a degraded state.
```
$ firewall-cmd --add-rich-rule='rule priority="-100" family="ipv4" source address="10.0.0.10" service …
```
> [th/rich-rule-check-service] fix(rich): validate service name of rich rule

- src/firewall/core/fw_config.py
- src/firewall/core/fw_zone.py
- src/firewall/core/io/direct.py
- src/firewall/core/io/helper.py
- src/firewall/core/io/icmptype.py
- src/firewall/core/io/io_object.py
- src/firewall/core/io/ipset.py
- src/firewall/core/io/lockdown_whitelist.py
- src/firewall/core/io/policy.py
- src/firewall/core/io/service.py
- src/firewall/core/io/zone.py
- src/firewall/errors.py
- src/firewall/server/firewalld.py
`IMPORT_EXPORT_STRUCTURE` is a tuple of (string,variant)-tuples.
Most callers are interested in the keys, and want to lookup. The tuple is cumbersome to use. Use a dictionary instead.
In the past, a dictionary was not suitable, because it did not preserver order. We require pyton 3.7, where dictionaries preserve order (and are iterated in the order of insertion).
> [th/import-export-structure] make IMPORT_EXPORT_STRUCTURE a dictionary

- src/firewall-config.in
- src/firewall/core/ipXtables.py
- src/firewall/core/nftables.py
- src/tests/features/forward_ports.at
This pull request fixes issues with logging of forwarded traffic.
- c769089: enable option in gui to log rich rule forwarded ports.
- Note: nflog logging still not available.
- 4962d49: log just forwarded ports, not all traffic.
- e5c807f: enable logging of forwarded ports on nftables backend.
- 1adf9d7: verify logging of forwarded ports.
Closes #1263
> fix(forward-port): log rich rule forwarded ports

- src/tests/unit/test_firewalld_conf.py
The officially used version of python-black is the one from the github action check, currently black==22.12.0.
On Fedora 39, we get black==23.7.0, which changes behaviors in some regard. This is a common issue, where newer/different versions of the formatter will give different results.
In this case, when we reformat the code base with black==23.7.0, then the result will also be correctly formatted according to black=22.12.0.
Do this reformatting, so that on Fedora 39 a run of black does not introduce any changes -- even if the used black version is not the officially suggested one.
This is for convenience of users of black 23.
> chore(tests): reformat "test_firewalld_conf.py" with black==23.7.0

- src/tests/Makefile.am
- src/tests/functions.at
In order to run polkit tests inside the container we must start systemd,
dbus-broker, and polkit. In order to do this we have to rework how the
container is built and start them with init.
> test(check-container): fix running of polkit tests

- contrib/fw-in-container/data/data-etc-polkit-1-rules-d-40-firewalld.rules
Messing with the polkit rules means that `make check-integration` will fail. It should pass by default in fw-in-container.
Now the "40-firewalld.rules" file does nothing. It's still useful to have, because whenever I want to edit the polkit rules for manual testing, it is cumbersome to find the right location for the file and the proper syntax. The "40-firewalld.rules" file helps with that.
> [th/fw-in-container-polkit-rules] improvement(fw-in-container): don'tdo anything in "40-firewalld.rules" polkit rule

- firewalld.spec
Restarting the firewalld daemon is not as seamless, as it maybe should be. In particular, it can reconfigure the firewall or temporarily drop important rules. That should be improved, but until restart is really seamless, it is harmful to do during package update.
The proper way install new package is offline upgrade and reboot. If the user knows better, they can upgrade packages without reboot. But then they must handle the restart of the affected packages, in a way that is safe and useful to them.
https://issues.redhat.com/browse/RHEL-19610
> [th/pkg-upgrade-no-restart] improvement(spec): don't restart firewalld on package upgrade

- contrib/fw-in-container/fw-in-container
- src/tests/functions.at
fw-in-container is useful for testing and development.
Note that it runs a rootless container. For non-root users, the netlink socket buffer is limited by /proc/sys/net/core/{rmem_max,wmem_max}. This causes various tests inside fw-in-container to fail. The test also cannot just bump that limit, because it's rootless (and because it would be an undesirable modification of the host).
However, it's useful to support running such tests also inside the container. All that we need, is that the user (as root) bumps those host wide limits.
Extend the script to detect that, so that it can run.
If you now want to run those tests, first issue a
```
echo 4096000 > /proc/sys/net/core/rmem_max
echo 4096000 > /proc/sys/net/core/wmem_max
echo 4096000 > /proc/sys/net/core/wmem_default
```
as root. You can …
> [th/fw-in-container-no-skip] improvement(fw-in-container): support running nftables test in container

- src/tests/functions.at
To have it easier to run a single test, add the filename to AT_KEYWORDS.
`-k features/forward_ports.at:199` then works.
Also, show that name as part of the test name, otherwise it's cumbersome to see the right name that can be used to run the test.
> [th/test-keywords] automatically add the filename to AT_KEYWORDS and show it

- config/Makefile.am
- config/services/iperf2.xml
- config/services/iperf3.xml
- po/POTFILES.in
Add service definitions for `iperf2` and `iperf3`.
> Add iperf{2,3} services

- src/firewall/core/fw.py
- src/firewall/core/fw_direct.py
- src/firewall/core/fw_policy.py
- src/firewall/core/fw_transaction.py
- src/firewall/core/fw_zone.py
I think most functions that have a `use_transaction` argument, should not optimally take a transaction. Instead, their callers should always provide one.
But that is not immediately obvious to fix, without potential changes in behavior (which may be correct). For example, there are calls like `transaction.add_pre(self._fw.flush_direct_backends)`, where the flush is not done with a transaction. Maybe it should be.
Anyway. Add and use a context manager for the "use_transaction" pattern, to simplify the code.
> [th/with-transaction] cleanup `use_transaction` handling

- config/firewalld.service.in
As part of https://fedoraproject.org/wiki/Changes/SystemdSecurityHardening which has been approved for Fedora 40, I am working on updating Systemd services to add additional hardening settings, please review this PR and let me know if you have any feedback. 
https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html has detailed information on each of these settings including the version of Systemd where they were introduced.
> improvement(config): update Systemd security settings

- config/Makefile.am
- config/services/ws-discovery-host.xml
- po/POTFILES.in
Add a generic service definition for a WS-Discovery host implementation,
which, e.g., allows to discover Samba file sharing services via Windows.
As per https://learn.microsoft.com/en-us/windows/win32/wsdapi/additional-ws-discovery-functionality,
TCP port 5357 is used by the service and respective implementations (see
below).
The file re-uses the already existing UDP multicast service definition.
The service file is taken from openSUSE (see
https://build.opensuse.org/package/view_file/openSUSE:Leap:15.5/wsdd/wsdd.xml),
which did not validate against the firewalld serivce schema. Thus, the
include statement was moved. The original author of the openSUSE
package, suggested to upstream a generic service definition that is
agnostic to a specific implementation, like wsdd …
> feat(service): add WS-Discovery host

- config/Makefile.am
- config/services/mndp.xml
- po/POTFILES.in
It's used by winbox to find devices over network using MNPD or CDP protocol.
> feat: add a service for MNPD protocol

- src/firewall/core/io/policy.py
- src/tests/features/forward_ports.at
If the destination address is the host then this is necessary. A policy with egress-zone=ANY does not work because the policy dispatch will match the egress zones "source" in the destination address.
> fix(policy): allow forward ports w/ to-addr for egress-zone=HOST

- src/tests/functions.at
- src/tests/regression/rhbz1855140.at
This changed in nftables commit 5fecd2a6ef61 ("src: disentangle ICMP code types").
> test(functions): nftables: normalize icmp reject codes

- config/services/ceph.xml
The highest port number used by Ceph was updated in https://github.com/ceph/ceph/pull/42210.
Fixes https://github.com/firewalld/firewalld/issues/1329
> fix(service): update highest port number for ceph

- src/firewall/server/decorators.py
Allow up to 60 seconds for polkit authorization. The current default is 25 seconds which can be a bit short for a user to type a password.
Fixes: #1328
> fix(polkit): allow 60 seconds for authorization

- config/firewalld.conf
- doc/xml/firewalld.conf.xml
- doc/xml/firewalld.dbus.xml
- src/firewall/config/__init__.py.in
- src/firewall/core/fw.py
- src/firewall/core/io/firewalld_conf.py
- src/firewall/core/ipXtables.py
- src/firewall/core/nftables.py
- src/firewall/server/config.py
- src/firewall/server/firewalld.py
- src/tests/dbus/firewalld.conf.at
- src/tests/features/rpfilter.at
- src/tests/functions.at
After these changes rpfilter supports the below options.
```
#
IPv6_rpfilter=strict
```
> feat(IPv6_filter): support loose and forward-only RPF checks

- config/Makefile.am
- config/services/stun.xml
- config/services/stuns.xml
- config/services/turn.xml
- config/services/turns.xml
- po/POTFILES.in
References:
STUN: [IETF RFC 8489](https://datatracker.ietf.org/doc/html/rfc8489)
TURN: [IETF RFC 8656](https://datatracker.ietf.org/doc/html/rfc8656)
STUN and TURN use the same ports and are very closely related and often end up used interchangeably.
> feat(service): stun and stuns protocols

- src/firewall-applet.in
Qt6 does not fallback to the normal icon if the -shields_up/-shields_down icons are missing, causing missing icons for the applet. Set the normal icon as fallback explicitly.
> fix(firewall-applet): Set fallback icons

- src/firewall-config.glade
Adding a width request ensures that the height of the label on the ICMP Filter panel won't become too large. This fixes the problem that the height of the window cannot fit in a 1366x768 display.
Closes: https://github.com/firewalld/firewalld/issues/312
> fix(firewall-config): Set width request for long label

- config/firewall-config.appdata.xml.in
- po/POTFILES.in
This allows to translate the text appearing in the AppStream metadata.
> fix(appdata): Mark metainfo translatable

- src/firewall-config.glade
This allows the main window to fit into smaller screens, regardless of the size of the labels.
This is a better and more general fix for https://github.com/firewalld/firewalld/issues/312.
> fix(firewall-config): Add long labels into a scrolled window

- Dockerfile
Fixes #1395 
Container was missing python3-dbus dependency.
This caused `firewalld` to fail to start and exist with
```
Traceback (most recent call last):
File "/usr/sbin/firewalld", line 17, in <module>
import dbus
ModuleNotFoundError: No module named 'dbus'
```
Verification
```
docker run -it --rm --privileged --entrypoint=/bin/sh quay.io/firewalld/firewalld:2.2.0
dnf install python3-dbus
bash /root/docker_start.sh
firewall-cmd --state
```
```
$ docker run -it --rm --privileged --entrypoint=/bin/sh quay.io/firewalld/firewalld:2.2.0
sh-5.1# dnf install python3-dbus
CentOS Stream 9 - BaseOS                                                                                                                                                                     322 kB/s | 8.3 MB     00:26 …
```
> add missing python3-dbus dependancy to container image

- config/Makefile.am
It needs `@INTLTOOL_XML_RULE@` instead of `@INTLTOOL_XML_NOMERGE_RULE@` to actually work.
> fix: Fix translating appdata file

- doc/xml/firewalld.policies.xml
Fixes typo in [firewalld.policies(5)](https://firewalld.org/documentation/man-pages/firewalld.policies.html) docs.
> docs(policy): fix typo

- src/firewall-config.in
It's impossible to create a rich rule because the Rich_Rule constructor is incorrecly invoked on lines 3404-3709 of src/firewall-config.in. Moreover, Rich_Rule attributes are set for its instance, which, due to the frozen state of Rich_Rule, leads to even more errors.
Basically, the fix is quite simple: just create a dictionary of attributes and pass them to the Rich_Rule constuctor at once.
> fix(firewall-config): fix rich rule creation

- src/firewall-config.in
Disable the rich rule creation button and make an early return from the on_richRuleDialog_changed function so that no errors are thrown when the element is invalid (e.g. no port is specified when the element is instance of Rich_Port).
> fix(firewall-config): don't create rich rule with invalid element

- src/firewall-config.in
When the service selection dialog opens and no service is set, you can't
select the first service in the list right away. You have to choose
another service and then select the first one. This happens due to the
unconditional disabling of the service selection button.
To resolve this issue, we can simply check whether the service is set by
verifying that the `old_service` param of the `service_select_dialog`
function is not empty.
> fix(firewall-config): allow selecting the first service in the list

- config/policies/gateway-dmz-to-HOST.xml
- config/policies/gateway-lan-to-HOST.xml
- config/policies/gateway-lan-to-work.xml
- config/policies/gateway-lan-to-world.xml
- config/policies/gateway-world-to-HOST.xml
- doc/xml/Makefile.am
- doc/xml/firewall-cmd.xml.in
- doc/xml/firewall-offline-cmd.xml
- doc/xml/firewalld.dbus.xml
- doc/xml/firewalld.policy-set-gateway.xml
- doc/xml/firewalld.policy-sets.xml
- src/firewall-cmd.in
- src/firewall-offline-cmd.in
- src/tests/dbus/policy_permanent_functional.at
- src/tests/dbus/policy_runtime_functional.at
- src/tests/features/policy.at
- src/tests/features/policy_disable.at
- src/tests/regression/gh1152.at
This PR introduces the idea of "policy sets". Policy sets are a collection of policies that serve as starting configuration for common use cases, e.g. a home router. This allows the user to get started quickly and then modify the set to their specific environment.
In the future, we could add more sets for other things, e.g. RFCs, firewall standards, etc.
```
FIREWALLD.POLICY-(5)                   firewalld.policy-sets                  FIREWALLD.POLICY-(5)
NAME
firewalld.policy-sets - Policy Sets
DESCRIPTION
What Are Policy Sets?
Policy sets are collections of policies that serve as starting configuration for specific
use cases, e.g. a home router. They provide an easy way to get started. Users may then fine
tune the configuration for their environment. Every policy set has a dedicated man …
```
> feat: add gateway policy set
